name: Build Containers for Prod & Push to Dockerhub

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      env:
        DOCKER_HUB: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_HUB_KEY: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo 'Docker Login'
        docker login -u $DOCKER_HUB -p $DOCKER_HUB_KEY
        echo 'Running build...'
        docker build -t my-app:latest .
        echo 'Pushing Image...'
        docker push telmo87/my-app:latest
        echo 'Done!'