name: Build Containers for Prod & Push to Dockerhub

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Build
    - uses: actions/checkout@v2
      env:
        DOCKER_HUB: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_HUB_KEY: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo 'Running build...'
        docker build -t my-app .
        docker run my-app
        echo 'Done!'